routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/redirect', 'HomeController@redirect')->name('redirect');
Route::get('/', 'HomeController@index')->name('home');
Route::get('about', 'HomeController@about')->name('about');
Route::get('faqs', 'HomeController@faqs')->name('faqs');
Route::get('contact', 'HomeController@contact')->name('contact');

Route::group(['prefix' => 'all-services'], function(){
    Route::get('/', 'ServicesController@index')->name('services');
    Route::get('/show-summary', 'ServicesController@showSummary')->name('services.show-summary');
    Route::get('/payment-complete', 'ServicesController@showDone')->name('services.show-done');

    Route::post('country-services', 'ServicesController@countryServices')->name('country.services');
    Route::post('service-operators', 'ServicesController@serviceOperators')->name('service.operators');
    Route::post('operator-products', 'ServicesController@operatorProducts')->name('operator.products');

    Route::post('save-order-details', 'ServicesController@saveOrderDetails')->name('save.service-order.details');
    Route::post('save-order-payment', 'ServicesController@saveOrderPayment')->name('save.service-order.payment');
});

Route::group(['prefix' => 'mobile-topup'], function(){
    Route::get('/', 'AirtimeController@index')->name('airtime');
    Route::get('/show-summary', 'AirtimeController@showSummary')->name('airtime.show-summary');
    Route::get('/payment-complete', 'AirtimeController@showDone')->name('airtime.show-done');
    
    Route::post('get-products', 'AirtimeController@getProducts')->name('airtime.products');
    Route::post('save-order-details', 'AirtimeController@saveOrderDetails')->name('save.airtime-order.details');
    Route::post('save-order-payment', 'AirtimeController@saveOrderPayment')->name('save.airtime-order.payment');
});

// Admin Routes
Route::get('admin/login', 'Admin\AdminLoginController@showLoginForm')->name('admin-login');
Route::post('admin/login', 'Admin\AdminLoginController@login')->name('admin-login-post');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function(){
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin-dashboard');
    
    Route::get('/cms/home-page', 'Admin\HomeSectionMetaController@index')->name('home-page');
    Route::post('/cms/home-page', 'Admin\HomeSectionMetaController@save')->name('home-page-save');

    Route::get('/cms/about-page', 'Admin\AboutSectionMetaController@index')->name('about-page');
    Route::post('/cms/about-page', 'Admin\AboutSectionMetaController@save')->name('about-page-save');

    Route::resource('/cms/faq', 'Admin\FaqController');
    Route::get('/cms/faq/status-change/{id}', 'Admin\FaqController@statusChange')->name('status-change');

    Route::get('/cms/contact-page', 'Admin\ContactController@index')->name('contact-page');
    Route::post('/cms/contact-page', 'Admin\ContactController@save')->name('contact-page-save');

    Route::get('/cms/social-links', 'Admin\SocialLinksMetaController@index')->name('social-links');
    Route::post('/cms/social-links', 'Admin\SocialLinksMetaController@save')->name('social-links-save');

    Route::get('customers', 'Admin\DashboardController@customers')->name('customer.list');
    Route::get('transactions/{cid?}', 'Admin\DashboardController@transactions')->name('transaction.list');

    Route::group(['prefix' => 'promo'], function(){
        Route::get('list', 'Admin\PromoController@index')->name('promo.list');
        Route::get('add', 'Admin\PromoController@add')->name('promo.add');
        Route::get('edit/{id}', 'Admin\PromoController@edit')->name('promo.edit');
        Route::get('delete/{id}', 'Admin\PromoController@delete')->name('promo.delete');
        Route::get('change-status/{id}/{status}', 'Admin\PromoController@changeStatus')->name('promo.change-status');
        Route::post('save/{id?}', 'Admin\PromoController@save')->name('promo.save');

        Route::post('get-operators', 'Admin\PromoController@getOperators')->name('promo.operators');
    });

    
    Route::get('/settings', 'Admin\GeneralSettingsController@index')->name('admin.settings');
    Route::post('/settings', 'Admin\GeneralSettingsController@store')->name('admin.settings.save');
});

Route::group(['prefix'=>'user','middleware'=>['auth']],function(){
    Route::get('/dashboard', 'UserController@index')->name('user.dashboard');
    Route::get('/profile-setting', 'UserController@profile')->name('user.profile');

    Route::post('update-email', 'UserController@updateEmail')->name('update.email');
    Route::post('update-password', 'UserController@updatePassword')->name('update.password');
    Route::post('update-personal-info', 'UserController@updatePersonalInfo')->name('update.personal_info');

    Route::get('repeat-service/{id}', 'UserController@repeatService')->name('repeat.service');
    Route::get('repeat-airtime/{id}', 'UserController@repeatAirtime')->name('repeat.airtime');
    
    Route::get('/profile', 'Admin\AdminProfileController@index')->name('admin-profile');
    Route::post('/profile', 'Admin\AdminProfileController@store')->name('admin-profile-save');
});

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html class="no-js " lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>@yield('title') | LetRecharge</title>
        <link rel="icon" href="favicon.ico" type="image/x-icon"> <!-- Favicon-->
        <link rel="stylesheet" href="{{ asset('admin/assets/plugins/bootstrap/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('admin/assets/plugins/dropify/css/dropify.min.css') }}">
        <link rel="stylesheet" href="{{ asset('admin/assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.css') }}"/>
        <link rel="stylesheet" href="{{ asset('admin/assets/plugins/charts-c3/plugin.css') }}"/>
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
        <link rel="stylesheet" href="{{ asset('admin/assets/plugins/jquery-datatable/dataTables.bootstrap4.min.css') }}">

        <link rel="stylesheet" href="{{ asset('admin/assets/plugins/morrisjs/morris.min.css') }}" />

        <!-- Custom Css -->
        <link rel="stylesheet" href="{{ asset('admin/assets/css/style.min.css') }}">
    </head>

    <body class="theme-purple">

        <!-- Page Loader -->
        <div class="page-loader-wrapper">
            <div class="loader">
                <div class="m-t-30"><img class="zmdi-hc-spin" src="{{ asset('admin/assets/images/loader.svg') }}" width="48" height="48" alt="Aero"></div>
                <p>Please wait...</p>
            </div>
        </div>

        <!-- Overlay For Sidebars -->
        <div class="overlay"></div> 

        <!-- Left Sidebar -->
        @include('admin.layouts.sidebar')

        @yield('content')

        <!-- Jquery Core Js --> 
        <script src="{{ asset('admin/assets/bundles/libscripts.bundle.js') }}"></script> <!-- Lib Scripts Plugin Js ( jquery.v3.2.1, Bootstrap4 js) --> 
        <script src="{{ asset('admin/assets/bundles/vendorscripts.bundle.js') }}"></script> <!-- slimscroll, waves Scripts Plugin Js -->

        <script src="{{ asset('admin/assets/bundles/jvectormap.bundle.js') }}"></script> <!-- JVectorMap Plugin Js -->
        <script src="{{ asset('admin/assets/bundles/sparkline.bundle.js') }}"></script> <!-- Sparkline Plugin Js -->
        <script src="{{ asset('admin/assets/bundles/c3.bundle.js') }}"></script>

        
        <script src="{{ asset('admin/assets/bundles/datatablescripts.bundle.js') }}"></script>
        <script src="{{ asset('admin/assets/plugins/jquery-datatable/buttons/dataTables.buttons.min.js') }}"></script>

        <script src="{{ asset('admin/assets/plugins/ckeditor/ckeditor.js') }}"></script> <!-- Ckeditor --> 
        <script src="{{ asset('admin/assets/plugins/dropify/js/dropify.min.js') }}"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script> <!-- Bootstrap Notify Plugin Js -->
        <script src="{{ asset('admin/assets/plugins/sweetalert/sweetalert.min.js') }}"></script> <!-- SweetAlert Plugin Js --> 

        <script src="{{ asset('admin/assets/bundles/mainscripts.bundle.js') }}"></script>
        <script src="{{ asset('admin/assets/js/pages/index.js') }}"></script>
        <script src="{{ asset('admin/assets/js/pages/forms/editors.js') }}"></script>
        <script src="{{ asset('admin/assets/js/pages/forms/dropify.js') }}"></script>
        <script src="{{ asset('admin/assets/js/pages/tables/jquery-datatable.js') }}"></script>

        <script type="text/javascript">
            @if(session('success'))
            toastr.success("{{ session('success') }}");
            @endifif(session('error'))
            toastr.error("{{ session('error') }}");
            @endif
        </script>
        @stack('js')
    </body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<!-- Left Sidebar -->
<aside id="leftsidebar" class="sidebar">
    <div class="navbar-brand">
        <button class="btn-menu ls-toggle-btn" type="button"><i class="zmdi zmdi-menu"></i></button>
        <a href="index.html"><img src="{{ asset('admin/assets/images/logo.png') }}" width="180" alt="Aero"></a>
    </div>
    <div class="menu">
        <ul class="list">
            <li>
                <div class="user-info justify-content-center">
                    <h4>{{ Auth::user()->name }}</h4>
                    <small>Super Admin</small>
                </div>
            </li>
            <li class="active open"><a href="{{ route('admin-dashboard') }}"><i class="zmdi zmdi-home"></i><span>Dashboard</span></a></li>
            <li><a href="{{ route('promo.list') }}"><i class="zmdi zmdi-label"></i><span>Promos</span></a></li>
            <li><a href="{{ route('customer.list') }}"><i class="zmdi zmdi-account"></i><span>Customers</span></a></li>
            <li><a href="{{ route('transaction.list') }}"><i class="zmdi zmdi-view-list-alt"></i><span>Transactions</span></a></li>
            <li><a href="{{ route('admin-profile') }}"><i class="zmdi zmdi-account"></i><span>Our Profile</span></a></li>
            <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-apps"></i><span>CMS</span></a>
                <ul class="ml-menu">
                    <li><a href="{{ route('home-page') }}">Homepage</a></li>
                    <li><a href="{{ route('about-page') }}">About Us</a></li>
                    <li><a href="{{ route('faq.index') }}">Faqs</a></li>
                    <li><a href="{{ route('contact-page') }}">Contact Us</a></li>   
                    <li><a href="{{ route('social-links') }}">Social Links</a></li>                   
                </ul>
            </li>
            <li><a href="{{ route('admin.settings') }}"><i class="zmdi zmdi-settings"></i><span>Settings</span></a></li>
            <li><a href="javascript:void(0);"
                onclick="event.preventDefault();
                document.getElementById('logout-form').submit();"><i class="zmdi zmdi-account"></i><span>Logout</span></a></li>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </ul>
    </div>
</aside>