routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/redirect', 'HomeController@redirect')->name('redirect');
Route::get('/', 'HomeController@index')->name('home');
Route::get('about', 'HomeController@about')->name('about');
Route::get('faqs', 'HomeController@faqs')->name('faqs');
Route::get('contact', 'HomeController@contact')->name('contact');

Route::group(['prefix' => 'all-services'], function(){
    Route::get('/', 'ServicesController@index')->name('services');
    Route::get('/show-summary', 'ServicesController@showSummary')->name('services.show-summary');
    Route::get('/payment-complete', 'ServicesController@showDone')->name('services.show-done');

    Route::post('country-services', 'ServicesController@countryServices')->name('country.services');
    Route::post('service-operators', 'ServicesController@serviceOperators')->name('service.operators');
    Route::post('operator-products', 'ServicesController@operatorProducts')->name('operator.products');

    Route::post('save-order-details', 'ServicesController@saveOrderDetails')->name('save.service-order.details');
    Route::post('save-order-payment', 'ServicesController@saveOrderPayment')->name('save.service-order.payment');
});

Route::group(['prefix' => 'mobile-topup'], function(){
    Route::get('/', 'AirtimeController@index')->name('airtime');
    Route::get('/show-summary', 'AirtimeController@showSummary')->name('airtime.show-summary');
    Route::get('/payment-complete', 'AirtimeController@showDone')->name('airtime.show-done');
    
    Route::post('get-products', 'AirtimeController@getProducts')->name('airtime.products');
    Route::post('save-order-details', 'AirtimeController@saveOrderDetails')->name('save.airtime-order.details');
    Route::post('save-order-payment', 'AirtimeController@saveOrderPayment')->name('save.airtime-order.payment');
});

// Admin Routes
Route::get('admin/login', 'Admin\AdminLoginController@showLoginForm')->name('admin-login');
Route::post('admin/login', 'Admin\AdminLoginController@login')->name('admin-login-post');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function(){
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin-dashboard');
    
    Route::get('/cms/home-page', 'Admin\HomeSectionMetaController@index')->name('home-page');
    Route::post('/cms/home-page', 'Admin\HomeSectionMetaController@save')->name('home-page-save');

    Route::get('/cms/about-page', 'Admin\AboutSectionMetaController@index')->name('about-page');
    Route::post('/cms/about-page', 'Admin\AboutSectionMetaController@save')->name('about-page-save');

    Route::resource('/cms/faq', 'Admin\FaqController');
    Route::get('/cms/faq/status-change/{id}', 'Admin\FaqController@statusChange')->name('status-change');

    Route::get('/cms/contact-page', 'Admin\ContactController@index')->name('contact-page');
    Route::post('/cms/contact-page', 'Admin\ContactController@save')->name('contact-page-save');

    Route::get('/cms/social-links', 'Admin\SocialLinksMetaController@index')->name('social-links');
    Route::post('/cms/social-links', 'Admin\SocialLinksMetaController@save')->name('social-links-save');

    Route::get('customers', 'Admin\DashboardController@customers')->name('customer.list');
    Route::get('transactions/{cid?}', 'Admin\DashboardController@transactions')->name('transaction.list');

    Route::group(['prefix' => 'promo'], function(){
        Route::get('list', 'Admin\PromoController@index')->name('promo.list');
        Route::get('add', 'Admin\PromoController@add')->name('promo.add');
        Route::get('edit/{id}', 'Admin\PromoController@edit')->name('promo.edit');
        Route::get('delete/{id}', 'Admin\PromoController@delete')->name('promo.delete');
        Route::get('change-status/{id}/{status}', 'Admin\PromoController@changeStatus')->name('promo.change-status');
        Route::post('save/{id?}', 'Admin\PromoController@save')->name('promo.save');

        Route::post('get-operators', 'Admin\PromoController@getOperators')->name('promo.operators');
    });

    
    Route::get('/settings', 'Admin\GeneralSettingsController@index')->name('admin.settings');
    Route::post('/settings', 'Admin\GeneralSettingsController@store')->name('admin.settings.save');
});

Route::group(['prefix'=>'user','middleware'=>['auth']],function(){
    Route::get('/dashboard', 'UserController@index')->name('user.dashboard');
    Route::get('/profile-setting', 'UserController@profile')->name('user.profile');

    Route::post('update-email', 'UserController@updateEmail')->name('update.email');
    Route::post('update-password', 'UserController@updatePassword')->name('update.password');
    Route::post('update-personal-info', 'UserController@updatePersonalInfo')->name('update.personal_info');

    Route::get('repeat-service/{id}', 'UserController@repeatService')->name('repeat.service');
    Route::get('repeat-airtime/{id}', 'UserController@repeatAirtime')->name('repeat.airtime');
    
    Route::get('/profile', 'Admin\AdminProfileController@index')->name('admin-profile');
    Route::post('/profile', 'Admin\AdminProfileController@store')->name('admin-profile-save');
});

app/Faq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    //
    protected $table='faqs';
    protected $primaryKey='id';
    protected $fillable = ['question','answer','status'];
}

app/Http/Controllers/Admin/FaqController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Faq;
use Auth;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $faqs = Faq::all();
        return view('admin.cms.faq.index', compact('faqs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.cms.faq.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'question' => 'required',
            'answer' => 'required',
        ]);
        $faq_add = Faq::create([
            'question' => $request->question,
            'answer' => $request->answer,
            'status' => $request->status ?? "0",
        ]);
        $notification = array(
            'message' => 'FAQ Added Successfully!'
        );
        return redirect()->route('faq.index')->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $faqs = Faq::findOrFail($id);
        return view('admin.cms.faq.edit', compact('faqs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'question' => 'required',
            'answer' => 'required',
        ]);

        $faq_update = Faq::where('id',$id)->update([
            'question' => $request->question,
            'answer' => $request->answer,
            'status' => $request->status ?? "0",
        ]);
        $notification = array(
            'message' => 'FAQ Updated Successfully!'
        );
        return redirect()->route('faq.index')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Faq::find($id)->delete();
        return response()->json();
    }

    public function statusChange($id){
        $faqs = Faq::findOrFail($id);

        if ($faqs->status == "1") {
            $faqs->status = "0";
            $faqs->save();
        } else {
            $faqs->status = "1";
            $faqs->save();
        }

        return response()->json();
        
    }
}

resources/views/admin/cms/faq/create.blade.php
@extends('admin.layouts.master')
@section('title','FAQs')
@section('content')
    <!-- Main Content -->

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>FAQs</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin-dashboard') }}"><i class="zmdi zmdi-home"></i> Let Recharge</a></li>
                    <li class="breadcrumb-item active">FAQs</li>
                </ul>
                <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <form class="form-horizontal" method="POST" action="{{ route('faq.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="body">
                            <div class="row clearfix">
                                <div class="col-lg-3 col-md-3 col-sm-4 form-control-label">
                                    <label for="question">Question</label>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-8">
                                    <div class="form-group">
                                        <input type="text" name="question" class="form-control" id="question" value="">
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-lg-3 col-md-3 col-sm-4 form-control-label">
                                    <label for="answer">Answer</label>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-8">
                                    <div class="form-group">
                                        <textarea name="answer" id="answer" class="ckeditor" value=""></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-lg-3 col-md-3 col-sm-4 form-control-label"></div>
                                <div class="col-md-9">
                                    <div class="checkbox">
                                        <input id="status" name="status" type="checkbox" value="1">
                                        <label for="status">
                                            Make Visible
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-raised btn-primary waves-effect">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection
@push('js')
<script>
    toastr.options = {
        "preventDuplicates": true
    }

    @if(count($errors) > 0)
        @foreach($errors->all() as $error)
            toastr.error("{{ $error }}");
        @endforeach
    @endif

    @if(Session::has('message'))
        toastr.success("{{ Session::get('message') }}");
    @endif
</script>
@endpush

resources/views/admin/cms/faq/edit.blade.php
@extends('admin.layouts.master')
@section('title','FAQs')
@section('content')
    <!-- Main Content -->

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>FAQs</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin-dashboard') }}"><i class="zmdi zmdi-home"></i> Let Recharge</a></li>
                    <li class="breadcrumb-item active">FAQs</li>
                </ul>
                <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <form class="form-horizontal" method="POST" action="{{ route('faq.update', $faqs->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="card">
                        <div class="body">
                            <div class="row clearfix">
                                <div class="col-lg-3 col-md-3 col-sm-4 form-control-label">
                                    <label for="question">Question</label>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-8">
                                    <div class="form-group">
                                        <input type="text" name="question" class="form-control" id="question" value="{{ $faqs->question }}">
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-lg-3 col-md-3 col-sm-4 form-control-label">
                                    <label for="answer">Answer</label>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-8">
                                    <div class="form-group">
                                        <textarea name="answer" id="answer" class="ckeditor" value="">{{ $faqs->answer }}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-lg-3 col-md-3 col-sm-4 form-control-label"></div>
                                <div class="col-md-9">
                                    <div class="checkbox">
                                        <input id="status" name="status" type="checkbox" value="1" @if ($faqs->status == "1") checked @endif>
                                        <label for="status">
                                            Make Visible
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-raised btn-primary waves-effect">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection
@push('js')
<script>
    toastr.options = {
        "preventDuplicates": true
    }

    @if(count($errors) > 0)
        @foreach($errors->all() as $error)
            toastr.error("{{ $error }}");
        @endforeach
    @endif

    @if(Session::has('message'))
        toastr.success("{{ Session::get('message') }}");
    @endif
</script>
@endpush

resources/views/admin/cms/faq/index.blade.php
@extends('admin.layouts.master')
@section('title','FAQs')
@section('content')
    <!-- Main Content -->

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>FAQs</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin-dashboard') }}"><i class="zmdi zmdi-home"></i> Let Recharge</a></li>
                    <li class="breadcrumb-item active">Faqs</li>
                </ul>
                <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="text-right">
                        <a href="{{ route('faq.create') }}" class="btn btn-primary">Add Faq</a>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Question</th>
                                        <th>Answer</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($faqs as $item)
                                    <tr data-id = {{ $item->id }}>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->question }}</td>
                                        <td>{!! $item->answer !!}</td>
                                        <td>
                                            @if ($item->status == 1)
                                                <span class="badge badge-success">Visible</span>
                                            @else
                                                <span class="badge badge-danger">Hidden</span>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="javascript:void(0);" class="btn btn-sm btn-success status-change" data-id ="{{ $item->id }}" title="Status Change"><i class="zmdi zmdi-mail-send"></i></a>
                                            <a href="{{ route('faq.edit', $item->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="zmdi zmdi-edit"></i></a>
                                            <a href="javascript:void(0);" class="btn btn-sm btn-danger delete" data-id ="{{ $item->id }}" title="Delete"><i class="zmdi zmdi-delete"></i></a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection
@push('js')
<script>
    $(document).on('click', '.delete', function (e) {
        e.preventDefault();
        var id = $(this).data('id');
        var token = "{{ csrf_token() }}";
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this FAQ!",
                icon: "warning",
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Yes!",
                showCancelButton: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        url : "{{ url('/')}}/admin/cms/faq" + '/' + id,
                        type : "DELETE",
                        data : {_token : token,id:id},
                        success: function(){
                            swal({
                                text: "Poof! Your FAQ has been deleted!",
                                icon: "success",
                            }).then(function(){ 
                                location.reload();
                                }
                            );
                        },
                        error : function(){
                            swal({
                                title: 'Opps...',
                                text : "There is and error",
                                type : 'error',
                                timer : '1500'
                            })
                        }
                    })
                } else {
                swal("Your imaginary file is safe!");
                }
            });
    });

    $(document).on('click', '.status-change', function (e) {
        e.preventDefault();
        var id = $(this).data('id');
        var token = "{{ csrf_token() }}";
            swal({
                title: "Are you sure?",
                text: "You Want To Change status",
                icon: "warning",
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Yes!",
                showCancelButton: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        url : "{{ url('/')}}/admin/cms/faq/status-change" + '/' + id,
                        type : "GET",
                        data : {_token : token,id:id},
                        success: function(){
                            swal({
                                text: "Poof! Status Changed",
                                icon: "success",
                            }).then(function(){ 
                                location.reload();
                                }
                            );
                        },
                        error : function(){
                            swal({
                                title: 'Opps...',
                                text : "There is an error",
                                type : 'error',
                                timer : '1500'
                            })
                        }
                    })
                } else {
                swal("Your imaginary file is safe!");
                }
            });
    });
    toastr.options = {
        "preventDuplicates": true
    }

    @if(count($errors) > 0)
        @foreach($errors->all() as $error)
            toastr.error("{{ $error }}");
        @endforeach
    @endif

    @if(Session::has('message'))
        toastr.success("{{ Session::get('message') }}");
    @endif
</script>
@endpush